#!/usr/bin/env python3
"""
Signal Logger - tracks BUY/SELL/HOLD signals generated by auto_trading.
Import this in hermes_auto_trading.py to log each signal.
"""

import json
import os
from datetime import datetime

SIGNAL_LOG_FILE = os.path.expanduser("~/hermes_signal_log.json")


def log_signal(signal: str, symbol: str, score: float, reasons: dict):
    """Log a trading signal."""
    today = datetime.now().strftime("%Y-%m-%d")
    
    # Load existing log
    if os.path.exists(SIGNAL_LOG_FILE):
        with open(SIGNAL_LOG_FILE) as f:
            log = json.load(f)
    else:
        log = {}
    
    # Initialize today
    if today not in log:
        log[today] = {"buy": 0, "sell": 0, "hold": 0, "trades": []}
    
    # Increment counter
    signal_lower = signal.lower()
    if signal_lower in log[today]:
        log[today][signal_lower] += 1
    
    # Log trade detail
    log[today]["trades"].append({
        "time": datetime.now().strftime("%H:%M:%S"),
        "symbol": symbol,
        "signal": signal,
        "score": round(score, 1),
        "reasons": reasons,
    })
    
    # Keep only last 30 days
    keys = sorted(log.keys())
    for old_key in keys[:-30]:
        del log[old_key]
    
    # Save
    with open(SIGNAL_LOG_FILE, "w") as f:
        json.dump(log, f, indent=2)


if __name__ == "__main__":
    # Test
    log_signal("BUY", "BTCUSDT", 65.5, {"micro": 60, "ta": 70, "oi": 55})
    print("Signal logged!")
